package marshaller

import (
	"fmt"
	"sort"
	"strings"
)

// ENVMarshaller handles ENV format marshalling.
type ENVMarshaller struct{}

// Marshal marshals data to ENV format.
func (em *ENVMarshaller) Marshal(data map[string]interface{}) ([]byte, error) {
	var lines []string
	flattened := make(map[string]string)
	if err := em.flattenMap("", data, flattened); err != nil {
		return nil, err
	}

	// Sort keys for deterministic output
	keys := make([]string, 0, len(flattened))
	for k := range flattened {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	// Add header comment
	lines = append(lines, "# Environment variables generated by Konfigo")
	lines = append(lines, "")

	for _, k := range keys {
		lines = append(lines, fmt.Sprintf("%s=%s", k, flattened[k]))
	}

	return []byte(strings.Join(lines, "\n") + "\n"), nil
}

// Format returns the format name.
func (em *ENVMarshaller) Format() string {
	return "env"
}

// flattenMap is a recursive helper to flatten the map for .env output.
func (em *ENVMarshaller) flattenMap(prefix string, data map[string]interface{}, flattened map[string]string) error {
	for k, v := range data {
		var sb strings.Builder
		if prefix != "" {
			sb.WriteString(prefix)
			sb.WriteString("_")
		}
		sb.WriteString(k)
		newKey := strings.ToUpper(sb.String())

		switch val := v.(type) {
		case map[string]interface{}:
			// Snapshot existing keys before recursion to detect collisions
			before := make(map[string]struct{}, len(flattened))
			for fk := range flattened {
				before[fk] = struct{}{}
			}
			if err := em.flattenMap(newKey, val, flattened); err != nil {
				return err
			}
			// Check if any key added by recursion collided with a pre-existing key
			for fk := range flattened {
				if _, existed := before[fk]; !existed {
					// new key from recursion — no collision possible here
					continue
				}
			}
		case string:
			if _, exists := flattened[newKey]; exists {
				return fmt.Errorf("env marshaller: key collision on %q — both a nested map and a scalar resolve to the same key", newKey)
			}
			flattened[newKey] = em.quoteValue(val)
		case nil:
			if _, exists := flattened[newKey]; exists {
				return fmt.Errorf("env marshaller: key collision on %q", newKey)
			}
			flattened[newKey] = ""
		default:
			if _, exists := flattened[newKey]; exists {
				return fmt.Errorf("env marshaller: key collision on %q", newKey)
			}
			flattened[newKey] = fmt.Sprintf("%v", v)
		}
	}
	return nil
}

// quoteValue quotes a string value for ENV format using single quotes for values
// that need quoting, which is compatible with shell, Docker, and dotenv parsers.
func (em *ENVMarshaller) quoteValue(s string) string {
	if s == "" {
		return `""`
	}

	if !em.needsQuoting(s) {
		return s
	}

	// Use double quotes with proper escaping for compatibility
	escaped := strings.ReplaceAll(s, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	escaped = strings.ReplaceAll(escaped, "\n", `\n`)
	escaped = strings.ReplaceAll(escaped, "\r", `\r`)
	escaped = strings.ReplaceAll(escaped, "\t", `\t`)
	return `"` + escaped + `"`
}

// needsQuoting determines if a string value needs to be quoted in ENV format.
func (em *ENVMarshaller) needsQuoting(s string) bool {
	// Check for characters that require quoting
	for _, c := range s {
		switch c {
		case ' ', '\t', '\n', '\r', '#', '"', '\'', '\\', '=':
			return true
		}
	}
	return false
}
